# Generated by Django 4.1.3 on 2022-11-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerblog', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
